### ISSUE TITLE
bazel build error about platforms

### ISSUE THREAD

**Issue by CSWYF3634076** [google/ghost-userspace#28] opened 2022-11-15 06:20 UTC
Ghost started with qemu
```sh
sudo qemu-system-x86_64 \
    -enable-kvm -cpu host -smp 2 -m 2048 -no-reboot -nographic \
    -kernel ghost-kernel/arch/x86/boot/bzImage \
    -drive id=root,media=disk,file=ubuntu.qcow2 \
    -net nic,macaddr=a6:5a:0d:31:01:46 -net tap,ifname=tap0 \
    -append "root=/dev/sda1 console=ttyS0"
 ```
When I build ghost-userspace, I get the following error
![image](https://user-images.githubusercontent.com/58356743/201840723-cc681223-44da-4e2d-9ee3-8fe71b62ba05.png)

```sh
ERROR: /root/.cache/bazel/_bazel_root/a45884f0d9c9471c8dde34f8ae70b628/external/bazel_tools/platforms/BUILD:64:6: in alias rule @bazel_tools//platforms:ios: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
ERROR: /root/.cache/bazel/_bazel_root/a45884f0d9c9471c8dde34f8ae70b628/external/bazel_tools/platforms/BUILD:64:6: Analysis of target '@bazel_tools//platforms:ios' failed
ERROR: /root/.cache/bazel/_bazel_root/a45884f0d9c9471c8dde34f8ae70b628/external/com_google_absl/absl/time/internal/cctz/BUILD.bazel:53:11: errors encountered resolving select() keys for @com_google_absl//absl/time/internal/cctz:time_zone
ERROR: Analysis of target '//:agent_biff' failed; build aborted: 
INFO: Elapsed time: 0.138s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

Is it because I started with qemu or because my bazel has a problem？

**Comment by dohyunkim-dev** [comment] 2023-01-03 23:42
Sorry for the delay - thanks for reporting this issue! I was able to replicate this issue with more recent bazel version and fixed with https://github.com/google/ghost-userspace/commit/1c8fd879e9d3c9f7246d36eb438ad9baf7c7c376. If you keep the bazel version to be 5.4.0 for now, it should compile. Feel free to follow up if the issue is not resolved.

**Closed by dohyunkim-dev** 2023-01-03 23:42 UTC
