### ISSUE TITLE
Issues running scheduler

### ISSUE THREAD

**Issue by IMaloney** [google/ghost-userspace#2] opened 2021-11-17 04:04 UTC
Hello, 

This may be a simple question but as I try to run the scheduler (currently fifo but issue arises with agent shinjuku as well), difficulties arise with the command 

```sudo bazel run fifo_agent```

Running this command produces the error 
```lib/enclave.cc:405(24972) CHECK FAILED: write(cpumask.c_str(), cpumask.length() == cpumask.length() [-1 != 2] errno: 16 [Device or resource busy]```
 
Upon closer inspection, I believe the issue has to do with the fact that I cannot read or write to any of the enclave folders or their subdirectories and files in 

```sys/fs/ghost/enclave_#/ctl```

Since I cannot write to files, write produces -1. This is true regardless of me being root or not. 

I was curious if there is anything I am missing in running ghost-user space or if there is a resolution to me not being able to write to the files in the enclave folder. 

I appreciate your help, thank you so much!

**Comment by jackhumphries** [comment] 2021-11-17 07:16
Hi,

Thanks for reaching out. Were you able to get the scheduler working at all at any point? That issue could come up for a variety of reasons (e.g., when an agent process previously crashed unexpectedly), so I want to pinpoint the cause.

Furthermore, for each `enclave_#` in `/sys/fs/`, does running `echo destroy > /sys/fs/enclave_#/ctl` (for each different enclave) and then starting the scheduler again fix the issue?

Jack

**Comment by IMaloney** [comment] 2021-11-17 07:50
Thank you for the response! I have not yet been able to get the scheduler running (it does not get past the initialization phase of any of the agents). Removing the ctl file helped progress creating the agent (it was necessary to change the permissions on the enclave folders in order to work). Afterwards, the program crashed when calling: 

```agent_bpf_init(tick_on_request)```

where the result produced was -1 due to the following line in bpf/user/agent.cc failing:

```err = agent_bpf_register(obj->progs.ghost_sched_skip_tick, BPF_GHOST_SCHED_SKIP_TICK);```

so I'm assuming that BPF_GHOST_SCHED_SKIP_TICK is greater than or equal to BPF_GHOST_SCHED_MAX_ATTACH_TYPE but I'm not sure why this is the case.

**Comment by jackhumphries** [comment] 2021-11-17 08:30
It seems more likely that the `if (bpf_registry[eat].prog)` branch was taken? Can you confirm the `errno` value?

**Comment by jackhumphries** [comment] 2021-11-17 08:33
Can you confirm the exact branch in `agent_bpf_init()` that detects the error?

**Comment by IMaloney** [comment] 2021-11-17 08:55
The error comes from the branch I initially denoted 

```
	if (eat >= BPF_GHOST_SCHED_MAX_ATTACH_TYPE) {
		errno = ERANGE;
		return -1;
	}
```

I added print statements in the agent_bpf_register function (one for error erange and the other for error  ebusy).

![error](https://user-images.githubusercontent.com/21049395/142168673-23978d9d-aa1f-4262-bde1-24a4e7bf1915.PNG)

**Comment by jackhumphries** [comment] 2021-11-17 09:24
We declare the enum that `BPF_GHOST_SCHED_SKIP_TICK` and `BPF_GHOST_SCHED_MAX_ATTACH_TYPE` members of in `bpf/user/agent.h`. We assign `BPF_GHOST_SCHED_SKIP_TICK` a value of 50 and then declare`BPF_GHOST_SCHED_MAX_ATTACH_TYPE` under the assumption that the compiler will give `BPF_GHOST_SCHED_MAX_ATTACH_TYPE` a value larger than 50 (probably 52).

Can you use a print statement to determine the value for each enum member and the post back here? I'm digging through some C spec pages to see if our assumption isn't guaranteed.

**Comment by IMaloney** [comment] 2021-11-17 10:19
Yep so after inspection it seems BPF_GHOST_SCHED_MAX_ATTACH_TYPE resolves to 
![error2](https://user-images.githubusercontent.com/21049395/142182151-2f6c1c07-1995-4c7d-b843-3cb80c7eff57.PNG)
0


I will try hard coding this value to 52 but what would be the correct way to resolve this enum?

**Comment by jackhumphries** [comment] 2021-11-17 10:42
Huh that's quite strange! What compiler are you using? Yes, hardcoding it to 52 should be good for now and perhaps I should update the codebase to give all the enum members hardcoded values.

Any existing app will work with ghOSt. You just need to move its threads into the ghOSt scheduling class. Look at the `GhostThread` class in `lib/ghost.h` which makes it easy to spawn pthreads that run in ghOSt. Alternatively, you can call `SchedTaskEnterGhost()` and passing existing thread TIDs as arguments to move threads into ghOSt.

Perhaps the best way to start is to write a simple program that spawns a single ghOSt thread and then joins it. Make sure to launch the ghOSt agent first and then launch the simple program.

There are a lot of tests in `tests/` and sample applications in `experiments/` that also show how to use ghOSt.

**Comment by brho** [comment] 2021-11-17 21:30
hi -

as far as destroying enclaves go, i have this one-liner in 'destroy.sh'.  (i don't squelch errors since i'm usually curious if i had any old enclaves or not)
```
for i in /sys/fs/ghost/enclave*/ctl; do echo destroy > $i; done
```

one caveat for SchedTaskEnterGhost is that you need to provide the ctl_fd for the enclave.  The GhostThread class handles that stuff for you.  alternatively, if you call ```GhostThread::SetGlobalEnclaveCtlFdOnce()```, then you can use SchedTaskEnterGhost without worrying about which enclave you join.  (You'll join the first one in ghostfs that has an agent attached).  it's a little gnarly.

regarding BPF_GHOST_SCHED_MAX_ATTACH_TYPE == 0, that certainly sounds odd.  when you hardcode it to 52, are you doing that inside the enum in bpf/user/agent.h? 

AFAIK, in an enum, an item without an equal is the previous item + 1, and 0 for the first.  (https://stackoverflow.com/a/30312219, which has a reference).

i'm fine with changing all the enums to use assignment.  it makes grep a little more useful.  =)  but i worry that there's some underlying issue floating around.

**Comment by NGUETOUM** [comment] 2022-01-17 11:45
Hello please how to change the permission in /sys/fs/ghost ?
I have try with root user to change it with the help of chmod command but the result was operation not permitted. 
Now I don't know how to proceed before to change the permission on that folder.
Please can you help me to solve this problem? 
I am using Ubuntu 20.04 with ghost-kernel 5.11.0+

**Comment by jackhumphries** [comment] 2022-01-18 03:05
Closing this. Feel free to reopen if you are still having this issue.

**Closed by jackhumphries** 2022-01-18 03:05 UTC

**Comment by NGUETOUM** [comment] 2022-01-21 00:40
Hello,
Please excuse me to reopen this issue but I have meet a similar error when I had try to run the command **bazel run agent_shinjuku** in a root mode. this is the error that I obtain:
![image](https://user-images.githubusercontent.com/19855011/150444047-73df4d6e-1836-41d1-8a42-25bb11a888c6.png)
I think that it because I don't have a right to write into **/sys/fs/ghost/** folder.
Please I don't know how I can  change the permission of that folder, since when I try to run the command: **sudo chmod -R 777 /sys/fs/ghost/** I just obtain **Operation is not permitted** as result.
Please I need your help.

**Comment by sarsanaee** [comment] 2022-07-19 14:22
Hi @jackhumphries 

`agent_bpf_register` fails again when running the BPF agent. `sudo ./bazel-bin/agent_biff`. The error is related to this if statement in the body of `agent_bpf_register`.

```
	if (eat >= BPF_GHOST_SCHED_MAX_ATTACH_TYPE) {
		errno = ERANGE;
		return -1;
	}
```


The problem is due to this part of the code again.

```
ifndef GHOST_BPF
// The definitions below are needed when the userspace code is compiled on a
// machine that is *not* running the ghOSt kernel and therefore does not have
// the ghOSt declarations below in the bpf.h UAPI header.

// From include/uapi/linux/bpf.h for the ghost kernel.

enum {
  BPF_PROG_TYPE_GHOST_SCHED = 1000,
  BPF_PROG_TYPE_GHOST_MSG,

  BPF_GHOST_SCHED_PNT = 2000,
  BPF_GHOST_MSG_SEND,
  BPF_GHOST_MAX_ATTACH_TYPE,  // __MAX_BPF_ATTACH_TYPE
};

// end include/uapi/linux/bpf.h

#else

#define BPF_GHOST_MAX_ATTACH_TYPE __MAX_BPF_ATTACH_TYPE

#endif
```
`__MAX_BPF_ATTACH_TYPE` is 37 based on what I have seen in the kernel, which is inconsistent with 2000 or 1000 values. 


Now you have got this structure in the kernel 

```
enum {
	/*
	 * There are arrays in the kernel that use MAX_BPF_ATTACH_TYPE, notably
	 * in kernel/bpf/cgroup.c.  That code will essentially ignore ghost
	 * programs.  Note that bpftool won't know about our types either.
	 *
	 * If we ever merge upstream, we can go back below
	 * __MAX_BPF_ATTACH_TYPE.  We have our own numbers to avoid rebase hell.
	 */
	BPF_GHOST_SCHED_PNT = 2000,
	BPF_GHOST_MSG_SEND,
	__MAX_BPF_GHOST_ATTACH_TYPE
};
```

Why don't you just use `__MAX_BPF_GHOST_ATTACH_TYPE` in the `bpf/user/agent.h`? Like `define BPF_GHOST_MAX_ATTACH_TYPE __MAX_BPF_GHOST_ATTACH_TYPE`

Thanks,
Alireza

**Comment by brho** [comment] 2022-07-20 14:16
so for you, in the "if eat >" check, BPF_GHOST_SCHED_MAX_ATTACH_TYPE 37?  can you printf that number, as well as BPF_GHOST_SCHED_PNT?

the intent of that ifndef in agent.h is to provide the ghost attach types if your kernel headers don't already have them.  if your kernel headers have them, then __MAX_BPF_ATTACH_TYPE should be 2002 in there.

**Comment by brho** [comment] 2022-07-20 18:02
crap - i'm looking at yet another copy of linux/bpf.h.  we'll get a fix out.

**Comment by sarsanaee** [comment] 2022-07-20 19:03
Hi @brho 

This sounds great! tnx :)
